---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myapp
  namespace: myapp
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: myapp
  url: https://github.com/mbn-ms-dk/gitops
