---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp
  namespace: myapp
spec:
  interval: 1m0s
  path: ./overlays/dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: gitops
  timeout: 3m0s
  wait: true
